src/Entity/Starship.php
<?php

namespace App\Entity;

use App\Entity\StarshipStatusEnum;
use App\Repository\StarshipRepository;
use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation\Slug;
use Gedmo\Mapping\Annotation\Timestampable;

#[ORM\Entity(repositoryClass: StarshipRepository::class)]
class Starship
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?string $name = null;

    #[ORM\Column]
    private ?string $class = null;

    #[ORM\Column]
    private ?string $captain = null;

    #[ORM\Column]
    private ?StarshipStatusEnum $status = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $arrivedAt = null;

    #[ORM\Column(unique: true)]
    #[Slug(fields: ['name'])]
    private ?string $slug = null;

    #[ORM\Column]
    #[Timestampable(on: 'update')]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\Column]
    #[Timestampable(on: 'create')]
    private ?\DateTimeImmutable $createdAt = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getClass(): ?string
    {
        return $this->class;
    }

    public function setClass(string $class): static
    {
        $this->class = $class;

        return $this;
    }

    public function getCaptain(): ?string
    {
        return $this->captain;
    }

    public function setCaptain(string $captain): static
    {
        $this->captain = $captain;

        return $this;
    }

    public function getStatus(): ?StarshipStatusEnum
    {
        return $this->status;
    }

    public function setStatus(StarshipStatusEnum $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getArrivedAt(): ?\DateTimeImmutable
    {
        return $this->arrivedAt;
    }

    public function setArrivedAt(\DateTimeImmutable $arrivedAt): static
    {
        $this->arrivedAt = $arrivedAt;

        return $this;
    }

    public function getStatusString(): string
    {
        return $this->status->value;
    }

    public function getStatusImageFilename(): string
    {
        return match ($this->status) {
            StarshipStatusEnum::WAITING => 'images/status-waiting.png',
            StarshipStatusEnum::IN_PROGRESS => 'images/status-in-progress.png',
            StarshipStatusEnum::COMPLETED => 'images/status-complete.png',
        };
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getUpdatedAt(): ?DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function checkIn(?DateTimeImmutable $arrivedAt = null): static
    {
        $this->setArrivedAt($arrivedAt ?? new DateTimeImmutable('now'));
        $this->setStatus(StarshipStatusEnum::WAITING);

        return $this;
    }
}

src/Entity/StarshipStatusEnum.php
<?php

namespace App\Entity;

enum StarshipStatusEnum: string
{
    case WAITING = 'waiting';
    case IN_PROGRESS = 'in progress';
    case COMPLETED = 'completed';
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Repository\StarshipRepository;
use Symfony\Component\HttpFoundation\Request;

class MainController extends AbstractController
{
    #[Route('/', name: 'app_homepage')]
    public function homepage(
        Request $request,
        StarshipRepository $starshipRepository,
    ): Response {
        $ships = $starshipRepository->findIncomplete();
        $ships->setMaxPerPage(5);
        $ships->setCurrentPage($request->query->get('page', 1));
        $myShip = $starshipRepository->findMyShip();

        return $this->render('main/homepage.html.twig', [
            'ships' => $ships,
            'myShip' => $myShip,
        ]);
    }
}

src/Controller/StarshipApiController.php
<?php

namespace App\Controller;

use App\Repository\StarshipRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/api/starships')]
class StarshipApiController extends AbstractController
{
    #[Route('', methods: ['GET'])]
    public function getCollection(StarshipRepository $repository): Response
    {
        $starships = $repository->findAll();

        return $this->json($starships);
    }

    #[Route('/{id<\d+>}', methods: ['GET'])]
    public function get(int $id, StarshipRepository $repository): Response
    {
        $starship = $repository->find($id);

        if (!$starship) {
            throw $this->createNotFoundException('Starship not found');
        }

        return $this->json($starship);
    }
}

src/Controller/StarshipController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Entity\Starship;
use Symfony\Bridge\Doctrine\Attribute\MapEntity;

class StarshipController extends AbstractController
{
    #[Route('/starships/{slug}', name: 'app_starship_show')]
    public function show(
        #[MapEntity(mapping: ['slug' => 'slug'])]
        Starship $starship
    ): Response {
        return $this->render('starship/show.html.twig', [
            'starship' => $starship,
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {% block stylesheets %}
        {% endblock %}

        {% block javascripts %}
{% block importmap %}{{ importmap('app') }}{% endblock %}
        {% endblock %}
    </head>
    <body class="text-white" style="background: radial-gradient(102.21% 102.21% at 50% 28.75%, #00121C 42.62%, #013954 100%);">
        <div class="flex flex-col justify-between min-h-screen relative">
            <div>
                <header class="h-[114px] shrink-0 flex flex-col sm:flex-row items-center sm:justify-between py-4 sm:py-0 px-6 border-b border-white/20 shadow-md">
                    <a href="{{ path('app_homepage') }}">
                        <img class="h-[42px]" src="{{ asset('images/starshop-logo.png') }}" alt="starshop logo">
                    </a>
                    {% set issData = get_iss_location_data() %}
                    <div>
                        <div title="Updated at: {{ issData.timestamp|date }}">
                            ISS Location ({{ issData.visibility }})
                        </div>
                        <p>Altitude: {{ issData.altitude }}</p>
                        <p>Latitude: {{ issData.latitude }}</p>
                        <p>Longitude: {{ issData.longitude }}</p>
                    </div>
                    <nav class="flex space-x-4 font-semibold">
                        <a class="hover:text-amber-400 pt-2" href="{{ path('app_homepage') }}">
                            Home
                        </a>
                        <a class="hover:text-amber-400  pt-2" href="#">
                            About
                        </a>
                        <a class="hover:text-amber-400 pt-2" href="#">
                            Contact
                        </a>
                        <a class="rounded-[60px] py-2 px-5 bg-white/10 hover:bg-white/20" href="#">
                            Get Started
                        </a>
                    </nav>
                </header>
                {% block body %}{% endblock %}
            </div>
            <div class="p-5 bg-white/5 mt-3 text-center">
                Made with ❤️ by <a class="text-[#0086C4]" href="https://symfonycasts.com">SymfonyCasts</a>
            </div>
        </div>
    </body>
</html>

templates/main/_shipStatusAside.html.twig
<aside
            data-controller="closeable"
            class="pb-8 lg:pb-0 lg:w-[411px] shrink-0 lg:block lg:min-h-screen text-white transition-all overflow-hidden px-8 border-b lg:border-b-0 lg:border-r border-white/20 transition-all overflow-hidden"
        >
            <div class="flex justify-between mt-11 mb-7">
                <h2 class="text-[32px] font-semibold">My Ship Status</h2>
                <button data-action="closeable#close">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 448 512"><!--!Font Awesome Pro 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2024 Fonticons, Inc.--><path fill="#fff" d="M384 96c0-17.7 14.3-32 32-32s32 14.3 32 32V416c0 17.7-14.3 32-32 32s-32-14.3-32-32V96zM9.4 278.6c-12.5-12.5-12.5-32.8 0-45.3l128-128c12.5-12.5 32.8-12.5 45.3 0s12.5 32.8 0 45.3L109.3 224 288 224c17.7 0 32 14.3 32 32s-14.3 32-32 32l-178.7 0 73.4 73.4c12.5 12.5 12.5 32.8 0 45.3s-32.8 12.5-45.3 0l-128-128z"/></svg>
                </button>
            </div>

            <div>
                <div class="flex flex-col space-y-1.5">
                    <div class="rounded-2xl py-1 px-3 flex justify-center w-32 items-center" style="background: rgba(255, 184, 0, .1);">
                        <div class="rounded-full h-2 w-2 bg-amber-400 blur-[1px] mr-2"></div>
                        <p class="uppercase text-xs">in progress</p>
                    </div>
                    <h3 class="tracking-tight text-[22px] font-semibold">
                        <a class="hover:underline" href="{{ path('app_starship_show', {
                            slug: myShip.slug
                        }) }}">{{ myShip.name }}</a>
                    </h3>
                </div>
                <div class="flex mt-4">
                    <div class="border-r border-white/20 pr-8">
                        <p class="text-slate-400 text-xs">Captain</p>
                        <p class="text-xl">{{ myShip.captain }}</p>
                    </div>

                    <div class="pl-8">
                        <p class="text-slate-400 text-xs">Class</p>
                        <p class="text-xl">{{ myShip.class }}</p>
                    </div>
                </div>
            </div>
        </aside>

templates/main/homepage.html.twig
{% extends 'base.html.twig' %}

{% block title %}Starshop: Beam up some parts!{% endblock %}

{% block body %}
    <main class="flex flex-col lg:flex-row">
        
        {{ include('main/_shipStatusAside.html.twig') }}

        <div class="px-12 pt-10 w-full">
            <h1 class="text-4xl font-semibold mb-8">
                Ship Repair Queue
            </h1>
            <div class="text-slate-400 mb-4">
                {{ ships.nbResults }} ships (Page {{ ships.currentPage }} of {{ ships.nbPages }})
            </div>
            <div class="space-y-5">
                   {% for ship in ships %}
                    <div class="bg-[#16202A] rounded-2xl pl-5 py-5 pr-11 flex flex-col min-[1174px]:flex-row min-[1174px]:justify-between">
                        <div class="flex justify-center min-[1174px]:justify-start">
                            <img class="h-[83px] w-[84px]" src="{{ asset(ship.statusImageFilename) }}" alt="Status: {{ship.statusString}}">
                            <div class="ml-5">
                                <div class="rounded-2xl py-1 px-3 flex justify-center w-32 items-center bg-amber-400/10">
                                    <div class="rounded-full h-2 w-2 bg-amber-400 blur-[1px] mr-2"></div>
                                    <p class="uppercase text-xs text-nowrap">{{ ship.statusString }}</p>
                                </div>
                                <h4 class="text-[22px] pt-1 font-semibold">
                                    <a
                                        class="hover:text-slate-200"
                                        href="{{ path('app_starship_show', {slug:ship.slug}) }}"
                                    >{{ ship.name }}</a>
                                </h4>
                                <div>
                                    {{ ship.arrivedAt|ago }}
                                </div>
                            </div>
                        </div>
                        <div class="flex justify-center min-[1174px]:justify-start mt-2 min-[1174px]:mt-0 shrink-0">
                            <div class="border-r border-white/20 pr-8">
                                <p class="text-slate-400 text-xs">Captain</p>
                                <p class="text-xl">{{ ship.captain }}</p>
                            </div>

                            <div class="pl-8 w-[100px]">
                                <p class="text-slate-400 text-xs">Class</p>
                                <p class="text-xl">{{ ship.class }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% if ships.haveToPaginate %}
                <div class="flex justify-around mt-3 underline font-semibold">
                    {% if ships.hasPreviousPage %}
                        <a href="{{ path('app_homepage', {page: ships.getPreviousPage}) }}">&lt; Previous</a>
                    {% endif %}
                    {% if ships.hasNextPage %}
                        <a href="{{ path('app_homepage', {page: ships.getNextPage}) }}">Next &gt;</a>
                    {% endif %}
                </div>
            {% endif %}
            <p class="text-lg mt-5 text-center md:text-left">
                Looking for your next galactic ride?
                <a href="#" class="underline font-semibold">Browse the {{ ships|length * 10 }} starships for sale!</a>
            </p>
        </div>
    </main>
{% endblock %}

templates/starship/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ starship.name }}{% endblock %}

{% block body %}
<div class="my-4 px-8">
    <a class="bg-white hover:bg-gray-200 rounded-xl p-2 text-black" href="{{ path('app_homepage') }}">
        <svg class="inline text-black" xmlns="http://www.w3.org/2000/svg" height="16" width="14" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path fill="#000" d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l160 160c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.2 288 416 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0L214.6 118.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-160 160z"/></svg>
        Back
    </a>
</div>
<div class="md:flex justify-center space-x-3 mt-5 px-4 lg:px-8">
    <div class="flex justify-center">
        <img class="max-h-[300px] md:max-h-[500px]" src="{{ asset('images/purple-rocket.png') }}" alt="purple ship launching">
    </div>
    <div class="space-y-5">
        <div class="mt-8 max-w-xl mx-auto">
            <div class="px-8 pt-8">
                <div class="rounded-2xl py-1 px-3 flex justify-center w-32 items-center bg-amber-400/10">
                    <div class="rounded-full h-2 w-2 bg-amber-400 blur-[1px] mr-2"></div>
                    <p class="uppercase text-xs">{{ starship.statusString }}</p>
                </div>

                <h1 class="text-[32px] font-semibold border-b border-white/10 pb-5 mb-5">
                    {{ starship.name }}
                </h1>
                <h4 class="text-xs text-slate-300 font-semibold mt-2 uppercase">Spaceship Captain</h4>
                <p class="text-[22px] font-semibold">{{ starship.captain }}</p>

                <h4 class="text-xs text-slate-300 font-semibold mt-2 uppercase">Class</h4>
                <p class="text-[22px] font-semibold">{{ starship.class }}</p>

                <h4 class="text-xs text-slate-300 font-semibold mt-2 uppercase">Ship Status</h4>
                <p class="text-[22px] font-semibold">30,000 lys to next service</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}